var words_in_english = ["acne","shoulder_pain","joint_pain","knee_pain","cough","Chest_pain","ear_ache","hair_fall","head_ache","skin_issue","stomach_ache","back_pain","neck_pain", "blurry_vision","hard_to_breath", "foot_ache"];
var words_in_sinhala = ["කුරුලෑ", "උරහිස් වේදනාව", "සන්ධි වේදනාව", "දණහිසේ වේදනාව", "කැස්ස", "පපුවේ වේදනාව", "කණ කැක්කුම", "හිසකෙස් කැක්කුම", "හිසේ කැක්කුම", "සමේ ගැටලුව", "බඩේ කැක්කුම", "පිටුපස වේදනාව", "බෙල්ලේ වේදනාව", "නොපැහැදිලි පෙනීම", "හුස්ම ගැනීමට අපහසු", "පාද කැක්කුම"];

var words_description_in_english =[["There is acne on my face",
                                   "My acne gets worse when it is hot",
                                   "My chest acne breaks out and never clears up",
                                   "There are some pimples on my face that bother me a lot",
                                   "I have pimples in patches along with a lot of redness on my face",
                                   "My acne itches and oozes",
                                   "I get clusters of pimples on my face that never go away",
                                   "I have pimples on my back",
                                   "My face is all broken out with pimples",
                                   "I get big patches of irritated pimples on my back and they hurt"],
                                   ["I can't move my shoulder because of pain",
                                   "I can't carry anything I have a pain in my shoulder",
                                   "I feel that is great pain in my left shoulder",
                                   "There is so much pain when I move my arm",
                                   "It hurts when I raise my arm up",
                                   "When I move on my shoulder, pain shoots down my arm",
                                   "My shoulder hurts me so much",
                                   "I have throbbing pain in my shoulder",
                                   "I have severe shoulder pain",
                                   "I feel shoulder pain at intervals of time"],
                                   ["I feel a lot of pain in the joints",
                                   "I feel joint pain every time I move",
                                   "when I extend my leg there is pain in knee joint",
                                   "I have pain like needles in my joints",
                                   "I can't move my leg, there is pain in the joint",
                                   "I feel a sharp pain in my ankle joint when I stand",
                                   "I feel a great pain in my shoulder joint and it does not go away",
                                   "I get I joint pain when I try to bend my leg or my arm",
                                   "I have a pain in my elbow joint",
                                   "The joints in my fingers are painful in the morning"],
                                   ["I feel pain in the knee after walking a long distance",
                                   "I feel pain in my knee",
                                   "I can't walk, my knee hurts me",
                                   "The pain is intense especially when I go down the stairs, it feels like something has snapped inside my knee.",
                                   "I could not exercise because of my knee pain",
                                   "My knees hurt so bad to walk that I stay sitting more than I should",
                                   "My knees seem to hurt as I go up or down stairs",
                                   "I have a lot of knee pain whenever I go running",
                                   "My knee feels weak and it gave way the other day at the top of the stairs",
                                   "When I walk up a flight of stairs, my right knee hurts"],
                                   ["I have a cold and it makes me cough alot",
                                   "I feel mucus trying to come up when I cough",
                                   "I'm suffering from sharp cough accompanied by  phlegm",
                                   "I cant sleep because of cough",
                                   "Have severe cold and cough",
                                   "I can`t stop coughing",
                                   "I have a very bad cough",
                                   "I have severe dry cough",
                                   "I've been over my cold for weeks but still cough every day",
                                   "The feeling of coughing increases in winter's reach"],
                                   ["I often get a sharp pain in my chest and I can't tell what I'm doing that might be triggering it",
                                   "I feel chest pain when I walk a lot",
                                   "I cannot bear this squeezing sensation I have in my chest",
                                   "severe pain in the upper left side of chest",
                                   "There is this pain that radiates from my chest up to my left arm",
                                   "I feel increased heart rate with a terrible pain in my chest",
                                   "It is like I have a needle pushing through my chest",
                                   "My chest hurts when I do exercise",
                                   "I feel my chest hurting after I ran a long distance",
                                   "There is crushing sensation on my chest and I can't sleep"],
                                   ["I get an ear ache when it is cold",
                                   "I have an ear ache that won't go away.  I don't have a cold or headache or any other symptoms.  Just an earache.",
                                   "My left ear is ok, but the right one feels like it's being stabbed with a nail.",
                                   "my ear hurts me badly",
                                   "My ear hurts and it's worse when I swallow",
                                   "Severe pain in the ear and I think there's fluid in my ears",
                                   "I have a sharp pain in my ear and the pain in my ear is unbearable",
                                   "I can't hear out of my ear properly, I feel like there is something in it causing pain.",
                                   "I have an ear ache when showering",
                                   "Hearing any loud sounds makes my ears ache"],
                                   ["My hair is falling out in huge amount",
                                   "When I brush my hair I notice big clumps of hair coming out in the brush",
                                   "I lose a lot of my hair",
                                   "My hair is coming out in chunks, especially when I wash it",
                                   "I'm in need for a treatment for my hair fall",
                                   "My hair always falls out and I have lost a lot of hair lately",
                                   "I notice a lot more hair coming out than usual when I brush my hair",
                                   "I've noticed my hair falling out a lot lately",
                                   "Every time I comb my hair there are so many hair in my comb.",
                                   "My hair is falling out in bunches"],
                                   ["I feel headache after reading a book for a long time",
                                   "I have front head pain and bright light bothers me",
                                   "I have a dull ache in my head",
                                   "my head hurts me badly",
                                   "When I'm tired I feel my head heavy",
                                   "I feel a great amount of pressure of my head",
                                   "My head hurts in the back and the pain lasts all day",
                                   "I have a headache almost every day",
                                   "My headache since I woke up this morning",
                                   "My head hurts and I lose the sensation in my face, then my vision is affected"],
                                   ["I have this strange skin rash on my arm",
                                   "I have dark spots on my skin",
                                   "My skin is very dry and peeling off",
                                   "My skin is itchy and inflamed",
                                   "I have a skin rash and it itches very bad.",
                                   "I feel severe itching in the skin with redness",
                                   "These red spots on my skin feels itchy",
                                   "My skin turned red on my back, I don't know why.",
                                   "I have dark patches of skin on my arm",
                                   "My skin feels itchy and I need to scratch my skin every minute"],
                                   ["I have a sharp pain in my lower stomach",
                                   "I feel pain in my stomach",
                                   "I often get a stomach ache after I eat",
                                   "I feel so sore in my stomach area",
                                   "I feel severe pain in the stomach",
                                   "My stomach feels starts hurting but then it feels better after I eat something mild",
                                   "My stomach has been sore since yesterday",
                                   "When I eat I feel my stomach hurts",
                                   "I have a severe stomach ache and I can't eat any thing",
                                   "I feel a burning sensation in my stomach after each meal"],
                                   ["I feel a pain in my back",
                                   "My back hurts me and I can't bend or walk",
                                   "I have a back pain since I fell on the floor.",
                                   "My back hurts a lot when I bend",
                                   "When I carry heavy things I feel like breaking my back",
                                   "My upper back has been sore for a week.",
                                   "I feel a pain in my back when I sit on a chair for long.",
                                   "I have a dull ache in  my lower back which makes it difficult to move",
                                   "I have shooting pains up and down my back.",
                                   "I can't stand up or sit down I have a pain in my back that annoys me"],
                                   ["I have a sharp pain in my neck",
                                   "I feel pain in my neck after waking up",
                                   "My neck feels stiff and I can't turn my neck",
                                   "I feel a pain in my neck",
                                   "I can't turn my neck to the left without feeling a stabbing pain",
                                   "There's swelling in my neck and it hurts",
                                   "I can't move my head up and down",
                                   "I can hardly move my neck.  It hurts.",
                                   "My neck hurts me I can't sleep bacause of it",
                                   "I have difficulty moving my neck"],
                                   ["I have cloudy eyes and I can't see well",
                                   "I have a problem in seeing objects it is too difficult to see",
                                   "I feel pain in my eyes I can see fog",
                                   "Everything looks like being in a smoky area",
                                   "I'm having a hard time reading because the letters are all fuzzy",
                                   "I am worried for my driving, because I can barely focus, my eyes feel teary",
                                   "I have a blurry vision since I woke up this morning",
                                   "I am having problems seeing things feel like a cloud on my eyes everything is blurry",
                                   "I have a blurry vision after my head was hit yesterday",
                                   "I was watching tv and suddenly have blurry vision"],
                                   ["I used to be out of breath after going up a dozen of stairs, but now I struggle to breath even when I sit down",
                                   "I feel that it's hard to breath for me specially after running or making any effort",
                                   "Sometimes I feel like a claw on my chest that leaves me breathless",
                                   "I feel a tightness in my chest I can't take my breath",
                                   "My heart is pumping fast and I'm having a hard time to breathe",
                                   "When I walk it's hard to breathe",
                                   "I walk every day but now I get short of breath after going only a short way",
                                   "I have difficulty in breathing in crowded places",
                                   "I can hardly breathe",
                                   "My nose is congested all the time that makes it hard for me to breathe"],
                                   ["I can't walk because I have a severe foot ache",
                                   "My foot is hurting so much",
                                   "I have a foot ache although I don't walk a lot",
                                   "I feel pain in my left foot",
                                   "After walking I have some pain in my feet",
                                   "My right foot hurts and I can't turn it",
                                   "I have a painful cramp in my feet",
                                   "I can't walk well I have an ache in my foot",
                                   "When I walk I get a stabbing pain on the top of my foot",
                                   "At first it feels really numb, but then a thousand needles start to prick through my foot"]];

var words_description_in_sinhala = [["මගෙ මුහුනෙ කුරුලෑවක් තියෙනවා",
                                    "මගෙ මුහුනෙ කුරුලෑව රස්නෙට නරක අතට හැරෙනවා",
                                    "මගේ පපුවේ කුරුලෑ කැඩී යනවා, කවදාවත් පිරිසිදු නොවේ",
                                    "මගේ මුහුණේ සමහර කුරුලෑ තියෙනවා, මට බොහෝ කරදර කරන",
                                    "මගේ මුහුණේ කුරුලෑ එක්ක රතු ලප තියෙනවා",
                                    "මගේ කුරුලෑ කැසීම සහ ගැලීම",
                                    "මගේ මුහුණේ කුරුලෑ පොකුරු තියෙනවා සහ ඒව කවදවත් නැති වෙන්නෙ නෑ",
                                    "මගේ පිටේ කුරුලෑ තියෙනවා",
                                    "මගේ මුහුණ කුරුලෑ වලින් විනාශ වෙලා",
                                    "මගේ පිටේ කුරුලෑ විශාල පැල්ලම් ඇති අතර ඒවා රිදෙනවා"],
                                    ["වේදනාව නිසා මගේ උරහිස චලනය කළ නොහැක",
                                    "මගේ උරහිසේ වේදනාවක් ඇති නිසා කිසිවක් මට රැගෙන යා නොහැක",
                                    "මට දැනෙන්නේ එය මගේ වම් උරහිසේ විශාල වේදනාවක් ලෙසයි",
                                    "මම මගේ අත චලනය කරන විට බොහෝ වේදනාවක් දැනෙනවා",
                                    "මම අත ඔසවන විට එය රිදෙනවා",
                                    "මම උරහිස සොලවන විට, මගේ අතට වේදනාව දැනෙනවා",
                                    "මගේ උරහිස ගොඩක් රිදෙනව",
                                    "මගේ උරහිසේ දැඩි වේදනාවක් ඇත",
                                    "මට දරුණු උරහිස් වේදනාවක් තිබ",
                                    "මට වරින් වර උරහිස් වේදනාව දැනේ"],
                                    ["මට සන්ධිවල ලොකු වේදනාවක් දැනෙනවා",
                                    "එහා මෙහා යන විට මට සන්ධිවල වේදනාවක් දැනෙනවා",
                                    "මම කකුල දිගු කරන විට දණහිසේ සන්ධිවල වේදනාව දැනෙනවා",
                                    "මගේ සන්ධිවල ඉඳිකටුවලින් අනිනවා වැනි වේදනාවක් දැනෙනවා",
                                    "මට මගේ කකුල එහා මෙහා කළ නොහැක, සන්ධිවල වේදනාවක් තියෙනවා",
                                    "මම සිටගෙන සිටින විට මගේ වළලුකර සන්ධියේ තියුණු වේදනාවක් දැනෙනවා",
                                    "මගේ උරහිස් සන්ධියේ විශාල වේදනාවක් දැනෙන අතර එය පහව යන්නේ නැත",
                                    "මගේ කකුල හෝ අත නැමීමට උත්සාහ කරන විට සන්ධිවල වේදනාවක් දැනේ",
                                    "මගේ වැලමිට සන්ධියේ වේදනාවක් තියෙනවා",
                                    "උදේ කාලයේ මගේ ඇඟිලිවල ඇති සන්ධිවල  වේදනාවක් දැනෙනවා"],
                                    ["දිගු දුරක් ඇවිදීමෙන් පසු මට දණහිසේ වේදනාවක් දැනේ",
                                    "මගේ දණහිසේ වේදනාවක් දැනෙනවා",
                                    "මට ඇවිදින්න බැහැ මගේ දණහිස මට රිදෙනවා",
                                    "වේදනාව තීව්‍ර වන්නේ විශේෂයෙන් මම පඩිපෙලෙන් බැස යන විට, මගේ දණහිසේ යමක් කැඩී ඇති බවක් දැනේ",
                                    "මගේ දණහිසේ වේදනාව නිසා මට ව්‍යායාම කිරීමට නොහැකියි",
                                    "ඇවිදීමට බැරි තරමටම මගේ දණහිස් දරුණු ලෙස රිදෙන අතර මම ඕනාවටත් වඩා වාඩි වී සිටිමි",
                                    "මම පඩිපෙල ඉහළට හෝ පහළට යන විට මගේ දණහිස් රිදෙන බවක් පෙනේ",
                                    "මම දුවන හැම වෙලාවකම දණහිසේ වේදනාවක් තියෙනවා",
                                    "මගේ දණහිස දුර්වල බවක් දැනෙනවා සහ එය කලින් දවසේ පඩි පෙළ මුදුනෙදි දැනුනා",
                                    "මම පඩි පෙළක් ඉහළට යන විට මගේ දකුණු දණහිස රිදෙනවා"],
                                    ["මට සෙම්ප්‍රතිශ්‍යාවක් තියෙනවා සහා ඒ නිසා මට කැස්ස හැදෙනවා",
                                    "මම කහින විට සෙම ඉහළට එනවා මට දැනෙනවා",
                                    "මම සෙම රෝගත් සමඟ දරුණු කැස්සකින් පෙළෙනවා",
                                    "කැස්ස නිසා මට නිදාගන්න බැහැ",
                                    "දරුණු සෙම්ප්‍රතිශ්‍යාව සහ කැස්ස තිබේ",
                                    "මට කැස්ස නතර කළ නොහැක",
                                    "මට ගොඩක් නරක කැස්සක් තියෙනවා",
                                    "මට තද වියළි කැස්සක් තියෙනවා",
                                    "මම හෙම්බිරිස්සාවෙන් සති ගණනාවක් මිදිල සිටියත් සෑම දිනකම කැස්ස තියෙනවා",
                                    "ශීත ඍතුවේ ළඟා වෙද්දිම කැස්ස වගේ දැනෙනවා"],
                                    ["මට බොහෝ විට මගේ පපුවේ තියුණු වේදනාවක් ඇති වන අතර එය ඇති වෙන්නෙ කුමක් දැයි කිව නොහැක",
                                    "මම ගොඩක් ඇවිදින විට මට පපුවේ වේදනාව දැනේ",
                                    "මගේ පපුවේ ඇති තෙරපුම මට දරාගත නොහැකිය",
                                    "පපුවේ ඉහළ වම් පැත්තෙහි දැඩි වේදනාව",
                                    "මගේ පපුවේ සිට මගේ වම් අත දක්වා වේදනාවක් ඇත",
                                    "මගේ පපුවේ දරුණු වේදනාවක් සමඟ හෘද ස්පන්දන වේගය වැඩි වන බවක් මට දැනේ",
                                    "හරියට මගේ පපුව හරහා ඉඳිකටුවක් අනිනවා වගේ",
                                    "මම ව්‍යායාම කරන විට මගේ පපුව රිදෙනවා",
                                    "මම බොහෝ දුර දිව ගිය පසු පපුව රිදෙනවා මට දැනෙනවා",
                                    "මගේ පපුවේ තැළුණු ගතියක් දැනෙන අතර මට නිදාගත නොහැක"],
                                    ["ශීත ඍතුවේ ළඟා වෙද්දිම කැස්ස වගේ දැනෙනවා",
                                    "මට කණ් කැක්කුමක් ඇති අතර එය නැති වෙන්නෙ නැත",
                                    "මගේ වම් කණ හොඳයි, නමුත් දකුණට දැනෙන්නේ එය නියපොත්තකින් අනින බවයි",
                                    "මගේ කණ මට දරුණු ලෙස රිදෙනවා",
                                    "මගේ කණ රිදෙනවා සහා එය වඩාත් දරුණුයි මම යමක් ගිල දමන්න විට",
                                    "කනේ දැඩි වේදනාවක් ඇති අතර මගේ කන්වල තරලයක් ඇති බව මම සිතමි",
                                    "මගේ කනේ තියුණු වේදනාවක් ඇති අතර කනෙහි වේදනාව දරාගත නොහැකිය",
                                    "මගේ කන හරියට ඇසෙන්නේ නැත, වේදනාවක් ඇති කරන යමක් එහි ඇති බව මට හිතෙනවා",
                                    "ස්නානය කිරීමේදී මට කන් කැක්කුම ඇති වෙනවා",
                                    "ඕනෑම ශබ්දයක් ඇහෙන විට මට කන් කැක්කුම ඇති වේ"],
                                    ["මගේ කොණ්ඩය විශාල වශයෙන් වැටෙනවා",
                                    "මම කොණ්ඩය පීරන විට බුරුසුව තුළ විශාල කෙස් කළඹක් තිබෙන බව දැක්කා",
                                    "මගේ කොණ්ඩය ගොඩක් නැති වෙනවා",
                                    "විශේෂයෙන් මම කොණ්ඩය සේදීමේදී, මගේ කොණ්ඩේ යනවා",
                                    "මගේ හිසකෙස් වැටීම සඳහා ප්‍රතිකාරයක් අවශ්‍යයි",
                                    "මගේ කොණ්ඩය නිතරම වැටෙන අතර මෑතකදී මට හිසකෙස් විශාල ප්‍රමාණයක් අහිමි වී ඇත",
                                    "මගේ කොණ්ඩය පීරන විට වෙනදාට වඩා බොහෝ හිසකෙස් ගැලවී යන බව දැනෙනවා",
                                    "මගේ කොණ්ඩය ගොඩක් ගැලවී යන බව දැක්කා",
                                    "මගේ කොණ්ඩය පීරන සෑම අවස්ථාවකම පනාවෙහි කෙස් ගොඩක් තියෙනවා",
                                    "මගේ කොණ්ඩය පොකුරු පිටින් ගැලවී යනවා"],
                                    ["දීර්ඝ කාලයක් තිස්සේ පොතක් කියවීමෙන් පසු මට හිසරදයක් දැනෙනවා",
                                    "මට ඉදිරිපස හිසේ වේදනාව ඇති අතර දීප්තිමත් ආලෝකය මට අපහසුයි",
                                    "මගේ ඔළුවේ තද කැක්කුමක් තියෙනවා",
                                    "මගේ හිස දරුණු ලෙස රිදෙනවා",
                                    "මට මහන්සියි වෙලාවට, මගේ හිස කැක්කුම වැඩී",
                                    "මගේ හිසෙහි විශාල පීඩනයක් දැනෙනවා",
                                    "මගේ හිස පිටුපසට රිදෙන අතර වේදනාව දවස පුරා පවතී",
                                    "මට සෑම දිනකම පාහේ හිසරදයක් තිබේ",
                                    "මගේ හිසරදය අද උදේ අවදි වූ වේලවේ සිටම තියෙනවා",
                                    "මගේ හිස රිදෙන අතර මගේ මුහුණේ සංවේදනය නැති වී යයි, එවිට එය මගේ පෙනීමට බලපායි"],
                                    ["මගේ අතේ අමුතු දදයක් තියෙනවා",
                                    "මගේ සමේ අඳුරු පැල්ලම් තියෙනවා",
                                    "මගේ සම ඉතා වියලි හා පතුරු ගැලවී තියෙනවා",
                                    "මගේ සම කසන සහ ඉදිමෙන සුලුයි",
                                    "මගේ සමේ දදයක් ඇති අතර එය ඉතා නරකයි",
                                    "මට දැඩි කැසීමක් දැනෙනවා සමේ රතු පැහැ වීමත් සමග",
                                    "මගේ සමේ මේ රතු ලප කසනවා වගේ දැනෙනව",
                                    "මගේ පිටේ සම රතු වෙලා, මම දන්නෙ නෑ ඒ ඇයි කියල",
                                    "මගේ අතේ සමේ අඳුරු පැල්ලම් තිබේ",
                                    "සම කැසීමේ ගතියක් මට දැනෙනවා සහ සෑම විනාඩියකම මගේ සම කැසීමට අවශ්‍යයි"],
                                    ["මගේ බඩේ පහළ තියුණු වේදනාවක් තියෙනවා",
                                    "මට මගේ බඩේ වේදනාවක් දැනෙනවා",
                                    "මට බොහෝ විට ආහාර ගැනීමෙන් පසු බඩේ කැක්කුමක් ඇති වේ",
                                    "මට තද බඩේ වේදනාවක් දැනෙනවා",
                                    "මට මගේ බඩේ දරුණු වේදනාවක් දැනෙනවා",
                                    "මගේ බඩ රිදෙන්න පටන් ගන්නවා නමුත් මම මෘදු දෙයක් කෑමෙන් පසුව තරමක සුවයක් දැනෙනවා",
                                    "ඊයේ සිට මගේ බඩේ වේදනාවක් දැනෙනවා",
                                    "මම කන විට මගේ බඩ රිදෙනවා දැනෙනවා",
                                    "මට දරුණු බඩේ කැක්කුමක් තියෙනවා සහ මට කිසිවක් කන්න බැහැ",
                                    "සෑම ආහාර වේලකටම පසු මගේ බඩ දැවෙන සංවේදීතාවයක් දැනෙනවා"],
                                    ["මට කොන්දේ වේදනාවක් දැනෙනවා",
                                    "මගේ කොන්ද රිදෙනවා සහ මට නැමෙන්න හෝ ඇවිදින්න බැහැ",
                                    "මගේ කොන්දේ වේදනාව තියෙන්නෙ මම බිම වැටුන දවසෙ ඉදලා",
                                    "මම නෑමී සිටින විට මගේ පිට ගොඩක් රිදෙනවා",
                                    "මම බර දේවල් උස්සන වෙලාවට මට හිතෙන්නෙ මගෙ කොන්ද කැඩෙනවා වගේ කියලයි",
                                    "මගෙ කොන්දෙ ඉහළ කොටසේ වේදනාව සතියක සිට තියෙනවා",
                                    "මම පුටුවේ වැඩි වෙලාවක් ඉඳගෙන සිටින විට කොන්දෙ වේදනාව  දැනෙනවා",
                                    "මගේ කොන්දෙ පහළ තද කැක්කුමක් තියෙන නිසා එහා මෙහා යන්න අපහසුයි",
                                    "මගේ පිටේ ඉහළට හා පහළට දැඩී වේදනාවක් දැනෙනවා",
                                    "මගේ කොන්දේ වේදනාව නිසා මට නැගී සිටීමට හෝ වාඩි වීමට නොහැකිය, එය මට විශාල කරදරයක්"],
                                    ["මගේ බෙල්ලේ තියුණු වේදනාවක් තියෙනවා",
                                    "අවදි වූ පසු මගේ බෙල්ලේ වේදනාවක් දැනේනවා",
                                    "මගේ බෙල්ලට තද ගතියක් දැනෙනවා සහ මගේ බෙල්ල හරවන්න බැහැ",
                                    "මගේ බෙල්ලේ වේදනාවක් දැනෙනවා",
                                    "මගේ බෙල්ල වමට හරවන්න බැහැ, පිහියෙන් අනින තරම් වේදනාවක් දැනෙන්නේ නැතිව",
                                    "මගේ බෙල්ලේ ඉදිමීමක් ඇති අතර එය රිදෙනවා",
                                    "මගේ හිස ඉහළ පහළ කරන්න අපහසුයි",
                                    "මගේ බෙල්ල අමාරුවෙන් හැරවිය හැකී, එය වේදනාත්මකයි",
                                    "මගේ බෙල්ල රිදෙන නිසා මට නිදාගන්න බැහැ",
                                    "මට බෙල්ල හැරවිමේ අපහසුතාවයක් තියෙනවා"],
                                    ["මට බොඳ වූ ඇස් ඇති අතර හොඳින් නොපෙනේ",
                                    "මට දේවල් දැකීමේ අපහසුතාවයක් ඇත",
                                    "මට ඇස්වල වේදනාවක් දැනෙනවා මට මීදුම දකින්න පුළුවන්",
                                    "හැම දෙයක්ම වගේ දුම් සහිත ප්‍රදේශයක තියෙනව වගේ",
                                    "අකුරු නොපැහැදිලි නිසා මට කියවීමට අපහසුතාවයක් තිබේ",
                                    "මගේ රිය පැදවීම ගැන මම කනස්සල්ලට පත්ව සිටිමි, මොකද මගේ දෑස් වෙහෙසට පත්වෙන නිසා අවධානය යොමු කළ හැක්කේ යාන්තමින්ය",
                                    "මම අද උදේ අවදි වූ වේලාවෙ සිට මට බොඳ වෙලා පෙනෙනවා",
                                    "මට දේවල් දැකිමේ අපහසුතාවයක් තියෙනවා හරියට මගේ ඇස්වල වලාකුළක් බැඳලා වගේ හැමදේම බොඳ වෙලා පෙනෙනවා",
                                    "ඊයේ මගේ හිසට පහරක් වැදුනට පස්සේ මට බොඳ වෙලා පේනවා",
                                    "මම රූපවාහිනිය නරඹමින් සිටි අතර හදිසියේම බොඳ වෙලා පෙනෙන්න ගත්තා"],
                                    ["මට පඩි පෙළවල් ගොඩකට නැඟීමෙන් පසු හුස්ම ගැනීමට අපහසුයි, නමුත් දැන් මම වාඩි වී සිටියදී පවා හුස්ම ගැනීමට අපහසුයි",
                                    "මට හුස්ම ගැනීමේ අපහසු බවක් දැනෙනවා, විශේෂයෙන් දිවීමේදි හො ඕනෑම කාර්යයකින් පසු",
                                    "සමහර විට මගේ පපුව නියපොත්තකින් අනිනව වගේ සහ එය මට හුස්ම ගැනීම පවා අපහසු කරය",
                                    "මගේ පපුවේ තද ගතියක් දැනෙනවා මට හුස්ම ගන්න බැහැ",
                                    "මගේ හදවත වේගයෙන් ගැහෙන අතර මට හුස්ම ගැනීමට අපහසු වේ",
                                    "මම ඇවිදින විට හුස්ම ගැනීමට අපහසුය",
                                    "මම සෑම දිනකම ඇවිදින නමුත් දැන් මට කෙටි දුරක් ගියත් හුස්ම ගැනීම අපහසුයි",
                                    "ජනාකීර්ණ ස්ථානවල හුස්ම ගැනීමට මට අපහසුතාවයක් ඇත",
                                    "මට හුස්ම ගන්න අමාරුයි",
                                    "මගේ නාසය හිර වෙන හැම වෙලාවකම මට හුස්ම ගන්න අමාරුයි"],
                                    ["මට දරුණු කකුල් කැක්කුමක් ඇති නිසා මට ඇවිදින්න බැහැ",
                                    "මගේ කකුල ගොඩක් රිදෙනවා",
                                    "මම වැඩිපුර ඇවිදින්නේ නැතත් මගේ කකුලේ කැක්කුමක් ඇත",
                                    "මගේ වම් කකුලේ වේදනාවක් දැනෙනවා",
                                    "ඇවිදීමෙන් පසු මගේ කකුල් වල යම් වේදනාවක් දැනෙනවා",
                                    "මගේ දකුණු කකුල රිදෙන අතර මට එය හැරවිය නොහැක",
                                    "මගේ පාදවල වේදනාකාරී කැක්කුමක් තිබේ",
                                    "මට හොඳින් ඇවිදින්න බැහැ මගේ පාදයේ කැක්කුමක් තියෙනවා",
                                    "මම ඇවිදින විට මගේ පාදයේ පිහියෙන් ඇනීමක් වගේ දැනේ",
                                    "මුලදී එය ඇත්තෙන්ම අපහසුතාවයක් නැති නමුත් පසුව ඉඳිකටු දහසක් පාදය හරහා යන බව දැනේ"]];