var words_in_english = ["acne","shoulder_pain","joint_pain","knee_pain","cough","Chest_pain","ear_ache","hair_fall","head_ache","skin_issue","stomach_ache","back_pain","neck_pain", "blurry_vision","hard_to_breath", "foot_ache"];
var words_in_tamil = ["பருக்கள்", "தோள்பட்டை வலி", "மூட்டு வலி", "முழங்கால் வலி", "இருமல்", "நெஞ்சு வலி", "காது வலி", "முடி கொட்டுகிறது", "தலை வலி", "தோல் பிரச்சினை", "வயிற்று வலி", "முதுகு வலி", "கழுத்து வலி", "மங்கலான பார்வை", "சுவாசிக்க கடினமாக உள்ளது", "பாத வலி"];

var words_description_in_english =[["There is acne on my face",
                                   "My acne gets worse when it is hot",
                                   "My chest acne breaks out and never clears up",
                                   "There are some pimples on my face that bother me a lot",
                                   "I have pimples in patches along with a lot of redness on my face",
                                   "My acne itches and oozes",
                                   "I get clusters of pimples on my face that never go away",
                                   "I have pimples on my back",
                                   "My face is all broken out with pimples",
                                   "I get big patches of irritated pimples on my back and they hurt"],
                                   ["I can't move my shoulder because of pain",
                                   "I can't carry anything I have a pain in my shoulder",
                                   "I feel that is great pain in my left shoulder",
                                   "There is so much pain when I move my arm",
                                   "It hurts when I raise my arm up",
                                   "When I move on my shoulder, pain shoots down my arm",
                                   "My shoulder hurts me so much",
                                   "I have throbbing pain in my shoulder",
                                   "I have severe shoulder pain",
                                   "I feel shoulder pain at intervals of time"],
                                   ["I feel a lot of pain in the joints",
                                   "I feel joint pain every time I move",
                                   "when I extend my leg there is pain in knee joint",
                                   "I have pain like needles in my joints",
                                   "I can't move my leg, there is pain in the joint",
                                   "I feel a sharp pain in my ankle joint when I stand",
                                   "I feel a great pain in my shoulder joint and it does not go away",
                                   "I get I joint pain when I try to bend my leg or my arm",
                                   "I have a pain in my elbow joint",
                                   "The joints in my fingers are painful in the morning"],
                                   ["I feel pain in the knee after walking a long distance",
                                   "I feel pain in my knee",
                                   "I can't walk, my knee hurts me",
                                   "The pain is intense especially when I go down the stairs, it feels like something has snapped inside my knee.",
                                   "I could not exercise because of my knee pain",
                                   "My knees hurt so bad to walk that I stay sitting more than I should",
                                   "My knees seem to hurt as I go up or down stairs",
                                   "I have a lot of knee pain whenever I go running",
                                   "My knee feels weak and it gave way the other day at the top of the stairs",
                                   "When I walk up a flight of stairs, my right knee hurts"],
                                   ["I have a cold and it makes me cough alot",
                                   "I feel mucus trying to come up when I cough",
                                   "I'm suffering from sharp cough accompanied by  phlegm",
                                   "I cant sleep because of cough",
                                   "Have severe cold and cough",
                                   "I can`t stop coughing",
                                   "I have a very bad cough",
                                   "I have severe dry cough",
                                   "I've been over my cold for weeks but still cough every day",
                                   "The feeling of coughing increases in winter's reach"],
                                   ["I often get a sharp pain in my chest and I can't tell what I'm doing that might be triggering it",
                                   "I feel chest pain when I walk a lot",
                                   "I cannot bear this squeezing sensation I have in my chest",
                                   "severe pain in the upper left side of chest",
                                   "There is this pain that radiates from my chest up to my left arm",
                                   "I feel increased heart rate with a terrible pain in my chest",
                                   "It is like I have a needle pushing through my chest",
                                   "My chest hurts when I do exercise",
                                   "I feel my chest hurting after I ran a long distance",
                                   "There is crushing sensation on my chest and I can't sleep"],
                                   ["I get an ear ache when it is cold",
                                   "I have an ear ache that won't go away.  I don't have a cold or headache or any other symptoms.  Just an earache.",
                                   "My left ear is ok, but the right one feels like it's being stabbed with a nail.",
                                   "my ear hurts me badly",
                                   "My ear hurts and it's worse when I swallow",
                                   "Severe pain in the ear and I think there's fluid in my ears",
                                   "I have a sharp pain in my ear and the pain in my ear is unbearable",
                                   "I can't hear out of my ear properly, I feel like there is something in it causing pain.",
                                   "I have an ear ache when showering",
                                   "Hearing any loud sounds makes my ears ache"],
                                   ["My hair is falling out in huge amount",
                                   "When I brush my hair I notice big clumps of hair coming out in the brush",
                                   "I lose a lot of my hair",
                                   "My hair is coming out in chunks, especially when I wash it",
                                   "I'm in need for a treatment for my hair fall",
                                   "My hair always falls out and I have lost a lot of hair lately",
                                   "I notice a lot more hair coming out than usual when I brush my hair",
                                   "I've noticed my hair falling out a lot lately",
                                   "Every time I comb my hair there are so many hair in my comb.",
                                   "My hair is falling out in bunches"],
                                   ["I feel headache after reading a book for a long time",
                                   "I have front head pain and bright light bothers me",
                                   "I have a dull ache in my head",
                                   "my head hurts me badly",
                                   "When I'm tired I feel my head heavy",
                                   "I feel a great amount of pressure of my head",
                                   "My head hurts in the back and the pain lasts all day",
                                   "I have a headache almost every day",
                                   "My headache since I woke up this morning",
                                   "My head hurts and I lose the sensation in my face, then my vision is affected"],
                                   ["I have this strange skin rash on my arm",
                                   "I have dark spots on my skin",
                                   "My skin is very dry and peeling off",
                                   "My skin is itchy and inflamed",
                                   "I have a skin rash and it itches very bad.",
                                   "I feel severe itching in the skin with redness",
                                   "These red spots on my skin feels itchy",
                                   "My skin turned red on my back, I don't know why.",
                                   "I have dark patches of skin on my arm",
                                   "My skin feels itchy and I need to scratch my skin every minute"],
                                   ["I have a sharp pain in my lower stomach",
                                   "I feel pain in my stomach",
                                   "I often get a stomach ache after I eat",
                                   "I feel so sore in my stomach area",
                                   "I feel severe pain in the stomach",
                                   "My stomach feels starts hurting but then it feels better after I eat something mild",
                                   "My stomach has been sore since yesterday",
                                   "When I eat I feel my stomach hurts",
                                   "I have a severe stomach ache and I can't eat any thing",
                                   "I feel a burning sensation in my stomach after each meal"],
                                   ["I feel a pain in my back",
                                   "My back hurts me and I can't bend or walk",
                                   "I have a back pain since I fell on the floor.",
                                   "My back hurts a lot when I bend",
                                   "When I carry heavy things I feel like breaking my back",
                                   "My upper back has been sore for a week.",
                                   "I feel a pain in my back when I sit on a chair for long.",
                                   "I have a dull ache in  my lower back which makes it difficult to move",
                                   "I have shooting pains up and down my back.",
                                   "I can't stand up or sit down I have a pain in my back that annoys me"],
                                   ["I have a sharp pain in my neck",
                                   "I feel pain in my neck after waking up",
                                   "My neck feels stiff and I can't turn my neck",
                                   "I feel a pain in my neck",
                                   "I can't turn my neck to the left without feeling a stabbing pain",
                                   "There's swelling in my neck and it hurts",
                                   "I can't move my head up and down",
                                   "I can hardly move my neck.  It hurts.",
                                   "My neck hurts me I can't sleep bacause of it",
                                   "I have difficulty moving my neck"],
                                   ["I have cloudy eyes and I can't see well",
                                   "I have a problem in seeing objects it is too difficult to see",
                                   "I feel pain in my eyes I can see fog",
                                   "Everything looks like being in a smoky area",
                                   "I'm having a hard time reading because the letters are all fuzzy",
                                   "I am worried for my driving, because I can barely focus, my eyes feel teary",
                                   "I have a blurry vision since I woke up this morning",
                                   "I am having problems seeing things feel like a cloud on my eyes everything is blurry",
                                   "I have a blurry vision after my head was hit yesterday",
                                   "I was watching tv and suddenly have blurry vision"],
                                   ["I used to be out of breath after going up a dozen of stairs, but now I struggle to breath even when I sit down",
                                   "I feel that it's hard to breath for me specially after running or making any effort",
                                   "Sometimes I feel like a claw on my chest that leaves me breathless",
                                   "I feel a tightness in my chest I can't take my breath",
                                   "My heart is pumping fast and I'm having a hard time to breathe",
                                   "When I walk it's hard to breathe",
                                   "I walk every day but now I get short of breath after going only a short way",
                                   "I have difficulty in breathing in crowded places",
                                   "I can hardly breathe",
                                   "My nose is congested all the time that makes it hard for me to breathe"],
                                   ["I can't walk because I have a severe foot ache",
                                   "My foot is hurting so much",
                                   "I have a foot ache although I don't walk a lot",
                                   "I feel pain in my left foot",
                                   "After walking I have some pain in my feet",
                                   "My right foot hurts and I can't turn it",
                                   "I have a painful cramp in my feet",
                                   "I can't walk well I have an ache in my foot",
                                   "When I walk I get a stabbing pain on the top of my foot",
                                   "At first it feels really numb, but then a thousand needles start to prick through my foot"]];

var words_description_in_tamil = [["என் முகத்தில் முகப்பரு உள்ளது",
                                    "என் முகப்பரு வெப்பமான நேரத்தில் மோசமடைகிறது",
                                    "என் மார்பிலுள்ள முகப்பரு உடைந்து ஒருபோதும் மாறுவதில்லை",
                                    "என் முகத்தில் உள்ள பருக்கள் எனக்கு மிகவும் தொந்தரவாக உள்ளன",
                                    "என் முகத்தில் நிறைய சிவந்த திட்டுகளாக பருக்கள் உள்ளன",
                                    "என் முகப்பருவால் அரிப்பு மற்றும் கசிவு ஏற்படுகிறது",
                                    "என் முகத்தில் கொத்துக்களாக உருவாகும் பருக்கள் மாறுவதில்லை",
                                    "என் முதுகில் பருக்கள் உள்ளன",
                                    "என் முகம் அனைத்தும் உடைந்த பருக்கள் உள்ளன",
                                    "என் முதுகில் பெரிய திட்டுகளாக உள்ள பருக்கள் வலிக்கின்றன"],
                                    ["வலி காரணமாக என்னால் தோள்பட்டை நகர்த்தமுடியவில்லை",
                                    "என் தோளில் வலி உள்ளது, எதையும் என்னால் சுமக்கமுடியவில்லை",
                                    "என் இடது தோள்பட்டையில் மிகுந்த வலி என்று நான் நினைக்கிறேன்",
                                    "நான் என் கையை நகர்த்தும்போது மிகவும் வலி இருக்கிறது",
                                    "நான் என் கையை உயர்த்தும்போது வலிக்கிறது",
                                    "நான் நகரும்போது, வலி என் தோளிலிருந்து கைவரை பரவும்",
                                    "என் தோள்பட்டை என்னை மிகவும் காயப்படுத்துகிறது",
                                    "என் தோளில் துடிக்கும் வலி இருக்கிறது",
                                    "எனக்கு கடுமையான தோள்பட்டை வலி உள்ளது",
                                    "இடைக்கிடை தோள்பட்டை வலியை உணர்கிறேன்"],
                                    ["நான் மூட்டுகளில் நிறைய வலியை உணர்கிறேன்",
                                    "நான் நகரும் போது மூட்டு வலியை உணர்கிறேன்",
                                    "நான் காலை நீட்டும்போது முழங்கால் மூட்டு வலி உள்ளது",
                                    "என் மூட்டுகளில் ஊசி குத்துவது போன்ற வலி எனக்கு இருக்கிறது",
                                    "என்னால் காலை நகர்த்த முடியவில்லை, மூட்டு வலி உள்ளது",
                                    "நான் நிற்கும்போது என் கணுக்கால் மூட்டில் ஒரு கூர்மையான வலியை உணர்கிறேன்",
                                    "என் தோள்பட்டை மூட்டில் ஒரு பெரிய வலியை நான் உணர்கிறேன், அது போகாது",
                                    "நான் என் காலை அல்லது என் கையை வளைக்க முயற்சிக்கும்போது எனக்கு மூட்டு வலி ஏற்படுகிறது",
                                    "என் முழங்கை மூட்டில் எனக்கு வலி உள்ளது",
                                    "காலையில் என் விரல் மூட்டுகள் வலிக்கின்றன"],
                                    ["நீண்ட தூரம் நடந்த பிறகு முழங்காலில் வலியை உணர்கிறேன்",
                                    "என் முழங்காலில் கடுமையான வலியை உணர்கிறேன்",
                                    "என்னால் நடக்க முடியாது, என் முழங்கால் என்னை காயப்படுத்துகிறது",
                                    "குறிப்பாக நான் படிக்கட்டுகளில் இறங்கும்போது வலி தீவிரமாக இருக்கிறது, என் முழங்காலுக்குள் ஏதோ நொறுங்கியது போல் உணர்கிறது.",
                                    "முழங்கால் வலி காரணமாக என்னால் உடற்பயிற்சி செய்ய முடியவில்லை",
                                    "என் முழங்கால்கள் நடக்கும்போது மோசமாக காயப்படுத்துவதால், நான் அதிகநேரம் உட்கார்ந்திருக்கிறேன்",
                                    "நான் படிக்கட்டுகளுக்கு ஏறும்போது அல்லது இறங்கும்போது என் முழங்கால் வலிக்கத் தொடங்குகின்றது",
                                    "நான் ஓடும்போதெல்லாம் எனக்கு முழங்காலில் மிகுந்த வலி இருக்கிறது",
                                    "என் முழங்கால் பலவீனமாக இருக்கிறது, அன்று படிக்கட்டில் ஏற முடியவில்லை",
                                    "நான் படிக்கட்டில் ஏறும்போது, என் வலது முழங்கால் வலிக்கிறது"],
                                    ["எனக்கு ஜலதோஷம் இருப்பதால் இருமல் உண்டாகிறது",
                                    "நான் இருமும்போது சளி மேலே வர முயற்சிப்பதை உணர்கிறேன்",
                                    "நான் சளியுடன் சேர்ந்து கூர்மையான இருமலால் அவதிப்படுகிறேன்",
                                    "இருமல் காரணமாக என்னால் தூங்கமுடியவில்லை",
                                    "கடுமையான சளி மற்றும் இருமல் உள்ளது",
                                    "என்னால் இருமலை நிறுத்தமுடியவில்லை",
                                    "எனக்கு மிகவும் மோசமான இருமல் இருக்கிறது",
                                    "எனக்கு கடுமையான வறட்டு இருமல் உள்ளது",
                                    "எனக்கு  தடிமன் மாறி பல வாரங்களாகியும் ஒவ்வொரு நாளும் இருமல் இருக்கிறது",
                                    "குளிர்காலத்தில் இருமல் உணர்வு அதிகரிக்கிறது"],
                                    ["எனக்கு அடிக்கடி நெஞ்சில் ஒரு கூர்மையான வலி இருக்கிறது, நான் என்ன செய்கிறேன் என்று தெரியவில்லை",
                                    "நான் நிறைய நடக்கும்போது எனக்கு நெஞ்சு வலி ஏற்படுகிறது",
                                    "என் நெஞ்சில் இருக்கும் இந்த அழுத்தும் உணர்வை என்னால் தாங்கமுடியவில்லை",
                                    "நெஞ்சின் மேல் இடது பக்கத்தில் கடுமையான வலி இருக்கிறது",
                                    "இந்த வலி என் நெஞ்சிலிருந்து என் இடது கை வரை பரவுகிறது",
                                    "என் நெஞ்சில் ஒரு பயங்கரமான வலி, இதயத் துடிப்பு அதிகரித்ததாக உணர்கிறேன்",
                                    "என் நெஞ்சின் வழியாக ஒரு ஊசி குத்துவது போல உள்ளது",
                                    "நான் உடற்பயிற்சி செய்யும்போது என் மார்பு வலிக்கிறது",
                                    "நான் நீண்ட தூரம் ஓடிய பிறகு என் மார்பு வலிக்கிறது",
                                    "என் நெஞ்சு நெருக்கப்படுவது போல இருக்கிறது, என்னால் தூங்க முடியவில்லை"],
                                    ["குளிராக இருக்கும்போது எனக்கு காது வலி வரும்",
                                    "எனக்கு மாறாத காது வலி உள்ளது, எனக்கு வேறு எந்த அறிகுறிகளும் இல்லை, காது வலி மட்டும் தான்",
                                    "என் இடது காது பரவாயில்லை, ஆனால் வலதுபுறம் அது ஆணியால் குத்தப்படுவதைப் போல உணர்கிறேன்",
                                    "என் காது என்னை மோசமாக காயப்படுத்துகிறது",
                                    "என் காது வலி நான் ஏதும் விழுங்கும்போது மோசமாக இருக்கிறது",
                                    "காதில் கடுமையான வலி மற்றும் என் காதுகளில் திரவம் இருப்பதாக நினைக்கிறேன்",
                                    "எனக்கு காதில் கூர்மையான வலி உள்ளது, காதில் வலி தாங்கமுடியவில்லை",
                                    "என் காதால் சரியாக கேட்க முடியாது, அதில் ஏதோ வலி இருப்பதாக உணர்கிறேன்",
                                    "தோயும் போது எனக்கு காது வலி உள்ளது",
                                    "எந்த உரத்த சத்தத்தையும் கேட்கும்போது என் காது வலிக்கிறது"],
                                    ["என் தலைமுடி பெரிய அளவில் கொட்டுகிறது",
                                    "நான் தலைமுடியை வாரும்போது, சீப்பில் தலைமுடி கொத்துகளாக வருவதை நான் கவனிக்கிறேன்",
                                    "நிறைய தலைமுடியை நான் இழக்கிறேன்",
                                    "என் தலைமுடி கொத்தாக வெளியே வருகிறது, குறிப்பாக நான் அதை கழுவும்போது",
                                    "என் தலைமுடி உதிர்தலுக்கு ஒரு சிகிச்சை தேவை",
                                    "என் தலைமுடி எப்போதும் கொட்டுகிறது, சமீபத்தில் நிறைய முடியை இழந்துவிட்டேன்",
                                    "நான் தலைமுடியை வாரும்போது வழக்கத்தை விட நிறைய முடி கொட்டுவதை நான் கவனிக்கிறேன்",
                                    "நான் சமீபத்தில் என் தலைமுடி நிறைய கொட்டுவதை கவனித்தேன்",
                                    "ஒவ்வொரு முறையும் நான் என் தலைமுடியை வாரும்போது என் சீப்பில் நிறைய முடி வருகின்றது",
                                    "என் தலைமுடி கொத்துக்களாக விழுகிறது"],
                                    ["ஒரு புத்தகத்தை நீண்ட நேரம் படித்த பிறகு எனக்கு தலைவலி ஏற்படுகிறது",
                                    "எனக்கு முன் பக்க தலை வலி மற்றும் பிரகாசமான ஒளி என்னை தொந்தரவு செய்கிறது",
                                    "என் தலையில் மந்தமான வலி உள்ளது",
                                    "என் தலை என்னை மோசமாக காயப்படுத்துகிறது",
                                    "நான் சோர்வாக இருக்கும்போது என் தலை கனமாக இருக்கிறது",
                                    "நான் என் தலையில் ஒரு பெரிய அளவு அழுத்தத்தை உணர்கிறேன்",
                                    "என் தலையின் பின்புறம் உள்ள வலி நாள் முழுவதும் நீடிக்கும்",
                                    "கிட்டத்தட்ட ஒவ்வொரு நாளும் எனக்கு தலைவலி இருக்கிறது",
                                    "இன்று காலை எழுந்ததிலிருந்து எனக்கு தலைவலி",
                                    "என் தலை வலிக்கிறது, என் முகத்தில் உள்ள உணர்வை இழப்பது போல் உணர்கிறேன்"],
                                    ["என் கையில் இந்த விசித்திரமான தோல் சொறி உள்ளது",
                                    "என் தோலில் கருமையான புள்ளிகள் உள்ளன",
                                    "என் தோல் மிகவும் வறண்டு உரிகின்றது",
                                    "என் தோலில் வீக்கத்தோடு அரிப்பும் உள்ளது",
                                    "என் தோலிலுள்ள சொறி மிகவும் மோசமாக இருக்கிறது",
                                    "சிவந்துள்ள தோலில் கடுமையான அரிப்பு இருப்பதை உணர்கிறேன்",
                                    "என் தோலிலுள்ள சிவப்பு புள்ளிகள் அரிப்பு ஏற்படுத்துகின்றன",
                                    "என் முதுகு தோல் சிவந்துள்ளது, ஏன் என்று எனக்குத் தெரியவில்லை",
                                    "என் கை தோலில் இருண்ட திட்டுகள் உள்ளன",
                                    "என் தோலில் அரிப்பு உணர்வு, ஒவ்வொரு நிமிடமும் என் தோலை சொறிந்து கொள்ளவேண்டி உள்ளது"],
                                    ["எனது கீழ் வயிற்றில் கூர்மையான வலி இருக்கிறது",
                                    "நான் என் வயிற்றில் வலியை உணர்கிறேன்",
                                    "நான் சாப்பிட்ட பிறகு அடிக்கடி வயிற்று வலி வரும்",
                                    "என் வயிற்றுப் பகுதியில் மிகவும் புண்ணாக இருக்கிறது",
                                    "நான் வயிற்றில் கடுமையான வலியை உணர்கிறேன்",
                                    "என் வயிறு வலிக்கத் தொடங்குகிறது, ஆனால் ஏதேனும் சாப்பிட்ட பிறகு பரவாயில்லை",
                                    "நேற்று முதல் என் வயிறு புண்ணாக உள்ளது",
                                    "நான் சாப்பிடும்போது என் வயிறு வலிக்கிறது",
                                    "எனக்கு கடுமையான வயிற்று வலி உள்ளது, என்னால் எதையும் சாப்பிட முடியாது",
                                    "ஒவ்வொரு தடவை சாப்பிட்டபிறகும் என் வயிற்றில் எரியும் உணர்வை உணர்கிறேன்"],
                                    ["என் முதுகில் ஒருவித வலியை உணர்கிறேன்",
                                    "என் முதுகு என்னை காயப்படுத்துகிறது, என்னால் குனியவோ நடக்கவோ முடியாது",
                                    "நான் தரையில் விழுந்ததிலிருந்து எனக்கு முதுகுவலி உள்ளது",
                                    "நான் குனியும்போது என் முதுகு ரொம்ப வலிக்கிறது",
                                    "நான் கனமான பொருட்களைச் சுமக்கும்போது என் முதுகு உடைவது போல் உணர்கிறேன்",
                                    "எனது மேல் முதுகு ஒரு வாரமாக புண்ணாக உள்ளது.",
                                    "நான் நீண்ட நேரம் நாற்காலியில் அமரும்போது என் முதுகில் ஒருவித வலி இருக்கிறது",
                                    "என் கீழ் முதுகில் மந்தமான வலி இருப்பதால் நகர்வது கடினமாக உள்ளது",
                                    "என் முதுகில் மேலும் கீழும் குத்தும் வலி உள்ளது",
                                    "என்னால் எழுந்து நிற்கவோ உட்காரவோ முடியாது என் முதுகு வலி எனக்கு எரிச்சலூட்டுகிறது"],
                                    ["என் கழுத்தில் கூர்மையான வலி இருக்கிறது",
                                    "நான் எழுந்த பிறகு என் கழுத்தில் வலியை உணர்கிறேன்",
                                    "என் கழுத்து கடினமாக இருப்பதாய் உணர்கிறேன், என்னால் கழுத்தை திருப்பமுடியவில்லை",
                                    "என் கழுத்தில் ஒரு வலி இருக்கிறது",
                                    "குத்துகிற வலியை உணராமல் என்னால் கழுத்தை இடது பக்கம் திருப்பமுடியாது",
                                    "என் கழுத்தில் வலியுடன்கூடிய வீக்கம் இருக்கிறது",
                                    "என்னால் தலையை மேலும் கீழும் நகர்த்த முடியாது",
                                    "கழுத்து வலியால் என்னால் கழுத்தை அசைப்பது கஷ்டமாக உள்ளது",
                                    "என் கழுத்து என்னை காயப்படுத்துகிறது, என்னால் தூங்கமுடியவில்லை",
                                    "என் கழுத்தை நகர்த்துவதில் எனக்கு சிரமம் உள்ளது"],
                                    ["என் கண்கள் மேகமூட்டமாக உள்ளன, என்னால் நன்றாக பார்க்கமுடியவில்லை",
                                    "பொருள்களைப் பார்ப்பதில் எனக்கு சிக்கல் உள்ளது, அதைப் பார்ப்பது மிகவும் கடினம்",
                                    "பார்வை தெளிவில்லாமல் இருக்கிறது, கண்களில் வலியை உணர்கிறேன்",
                                    "எல்லாம் புகையான பகுதியில் இருப்பது போல்  மங்கலாக தெரிகிறது",
                                    "எழுத்துக்கள் தெளிவில்லாமல் மங்கலாக இருப்பதால் படிக்க கடினமாக இருக்கிறது",
                                    "வாகனம் ஓட்டுவதில் என்னால் கவனம் செலுத்தமுடியவில்லை, என் கண்கள் சோர்வடைகின்றன",
                                    "இன்று காலை நான் எழுந்ததிலிருந்து எனக்கு மங்கலான பார்வை இருக்கிறது",
                                    "என் கண்களில் ஒரு மேகம் போல் எல்லாம் மங்கலாக தெரிகிறது, பார்ப்பதில் எனக்கு சிக்கல் உள்ளது",
                                    "நேற்று என் தலையில் அடிபட்டதிலிருந்து எனக்கு மங்கலான பார்வை இருக்கிறது",
                                    "நான் தொலைக்காட்சியைப் பார்த்துக் கொண்டிருந்தேன், திடீரென்று மங்கலான பார்வை ஏற்பட்டது"],
                                    ["நான் ஒரு டஜன் படிக்கட்டுகளில் ஏறிய பிறகு மூச்சு விடமுடியாமல் இருந்தேன், ஆனால் இப்போது நான் உட்கார்ந்துள்ள போதும் மூச்சு விட சிரமப்படுகிறேன்",
                                    "ஓடியபின் அல்லது ஏதும் வேலை செய்தபின் எனக்கு மூச்சு விடுவது கடினம் என்று நினைக்கிறேன்",
                                    "சில நேரங்களில் என் மார்பில் ஒரு இறுக்கம் இருப்பது போல் உணர்கிறேன், அதனால் மூச்சு விடமுடியாமல் இருக்கிறது",
                                    "என் மார்பில் ஒரு இறுக்கத்தை உணர்கிறேன், என்னால் மூச்சு எடுக்க முடியாது",
                                    "என் இதயம் வேகமாக துடிக்கிறது, எனக்கு சுவாசிக்க கடினமாக இருக்கிறது",
                                    "நான் நடக்கும்போது சுவாசிப்பது கடினமாக உள்ளது",
                                    "நான் ஒவ்வொரு நாளும் நடக்கிறேன், ஆனால் இப்போது ஒரு சிறிய தூரம் சென்ற பிறகு எனக்கு மூச்சுத் திணறல் ஏற்படுகிறது",
                                    "நெரிசலான இடங்களில் சுவாசிப்பது எனக்கு சிரமமாக உள்ளது",
                                    "என்னால் மூச்சு விட முடியாது",
                                    "எனக்கு எல்லா நேரத்திலும் மூக்கடைப்பு இருப்பதால் சுவாசிக்க கடினமாக உள்ளது"],
                                    ["எனக்கு கடுமையான கால் வலி இருப்பதால் என்னால் நடக்க முடியாது",
                                    "என் கால் மிகவும் வலிக்கிறது",
                                    "நான் நிறைய நடக்கவில்லை என்றாலும் எனக்கு கால் வலி உள்ளது",
                                    "என் இடது பாதத்தில் வலியை உணர்கிறேன்",
                                    "நடந்த பிறகு என் காலில் சிறிது வலி இருக்கிறது",
                                    "என் வலது கால் வலிக்கிறது, என்னால் அதை திருப்ப முடியாது",
                                    "என் காலில் ஒரு வலியுடன்கூடிய தசைப்பிடிப்பு உள்ளது",
                                    "என்னால் நன்றாக நடக்க முடியாது என் காலில் வலி உள்ளது",
                                    "நான் நடக்கும்போது என் காலின் மேல் ஒரு குத்தல் வலி வருகிறது",
                                    "முதலில் அது உணர்ச்சியற்றதாக உணர்கிறது, ஆனால் பின்னர் ஆயிரம் ஊசிகள் என் கால் வழியாக குத்த ஆரம்பிப்பது போல் உள்ளது"]];
